spring:
  data:
    mongodb:
      database: flora
security:
  path-to-allowed-origins: allowed-origins.json
  jwt:
    expirationInDays: 7
    # https://generate.plus/en/base64
    # with a configuration: 32 bytes length
    secret: VLlTboNwSJ7IqoNbt2CMAo26Di4Knfi9MM1wqvbM4oc=
