
export enum Hydrophile {
    XEROPHYTE = "XEROPHYTE",
    MESOPHYTE = "MESOPHYTE",
    SCLEROPHYTE = "SCLEROPHYTE",
    HYDROPHYTE = "HYDROPHYTE",
    HYGROPHYTE = "HYDROPHYTE",
    UNDEFINED = "UNDEFINED",
}
