
export enum Hydrophile {
    XEROPHYTE = "XEROPHYTE",
    MESOPHYTE = "MESOPHYTE",
    SCLEROPHYTE = "SCLEROPHYTE",
    HYDROPHYTE = "HYDROPHYTE",
    HYGROPHYTE = "HYGROPHYTE",
    UNDEFINED = "UNDEFINED",
    MESOXEROPHYTE = "MESOXEROPHYTE",
    MESOHYDROPHYTE = "MESOHYDROPHYTE",
    MESOHYGROPHYTE = "MESOHYGROPHYTE"
}
